import { EXTENSION_PROBE_ORDER } from "../../core/runner.js";

interface BashTemplateOptions {
  readonly name: string;
  readonly dirs: readonly string[];
}

/**
 * Generate a bash shell function that acts as a CLI dispatcher.
 */
export function generateBashFunction(options: BashTemplateOptions): string {
  const { name, dirs } = options;
  const dirsArray = dirs.map((d) => `"${d}"`).join(" ");
  const extProbe = EXTENSION_PROBE_ORDER.map((e) => `"${e}"`).join(" ");

  return `# Generated by pocket — https://github.com/rodrigopsasaki/pocketcli

function ${name}() {
  local __pocket_dirs=(${dirsArray})
  local __pocket_name="${name}"

  case "\$1" in
    help|doctor|completions|create)
      local -a __pocket_dir_flags=(); for __pocket_d in "\${__pocket_dirs[@]}"; do __pocket_dir_flags+=(--dir "\$__pocket_d"); done
      command pocket "\$1" --name "\$__pocket_name" "\${__pocket_dir_flags[@]}"
      return \$?
      ;;
    "")
      local -a __pocket_dir_flags=(); for __pocket_d in "\${__pocket_dirs[@]}"; do __pocket_dir_flags+=(--dir "\$__pocket_d"); done
      command pocket help --name "\$__pocket_name" "\${__pocket_dir_flags[@]}"
      return \$?
      ;;
  esac

  local __pocket_exts=(${extProbe})
  local __pocket_script="" __pocket_dir="" __pocket_depth=0
  local __pocket_argc=\$#
  local __pocket_args=("\$@")
  local __pocket_found=0

  for __pocket_d in "\${__pocket_dirs[@]}"; do
    for (( __pocket_i=__pocket_argc; __pocket_i>=1; __pocket_i-- )); do
      local __pocket_path="\$__pocket_d"
      local __pocket_ok=1

      for (( __pocket_j=0; __pocket_j<__pocket_i-1; __pocket_j++ )); do
        __pocket_path="\$__pocket_path/\${__pocket_args[\$__pocket_j]}"
        if [[ ! -d "\$__pocket_path" ]]; then
          __pocket_ok=0
          break
        fi
      done
      [[ \$__pocket_ok -eq 0 ]] && continue

      local __pocket_leaf="\${__pocket_args[\$(( __pocket_i - 1 ))]}"
      local __pocket_base="\$__pocket_path/\$__pocket_leaf"

      for __pocket_ext in "\${__pocket_exts[@]}"; do
        if [[ -f "\$__pocket_base.\$__pocket_ext" ]]; then
          __pocket_script="\$__pocket_base.\$__pocket_ext"
          __pocket_dir="\$__pocket_d"
          __pocket_depth=\$__pocket_i
          __pocket_found=1
          break 3
        fi
      done

      if [[ -f "\$__pocket_base" && ! -d "\$__pocket_base" ]]; then
        __pocket_script="\$__pocket_base"
        __pocket_dir="\$__pocket_d"
        __pocket_depth=\$__pocket_i
        __pocket_found=1
        break 2
      fi
    done
  done

  if [[ \$__pocket_found -eq 0 ]]; then
    echo "\$__pocket_name: command not found: \$*" >&2
    echo "Run '\$__pocket_name help' to see available commands." >&2
    return 127
  fi

  local __pocket_runner="" __pocket_runner_args=""
  case "\$__pocket_script" in
    *.sh|*.bash) __pocket_runner="bash" ;;
    *.zsh)       __pocket_runner="zsh" ;;
    *.py)        __pocket_runner="python3" ;;
    *.rb)        __pocket_runner="ruby" ;;
    *.js)        __pocket_runner="node" ;;
    *.ts)        __pocket_runner="npx" __pocket_runner_args="tsx" ;;
    *.php)       __pocket_runner="php" ;;
    *.pl)        __pocket_runner="perl" ;;
    *)
      local __pocket_shebang
      __pocket_shebang=\$(head -1 "\$__pocket_script" 2>/dev/null)
      if [[ "\$__pocket_shebang" == "#!/usr/bin/env "* ]]; then
        __pocket_runner="\${__pocket_shebang#\\#\\!/usr/bin/env }"
        __pocket_runner="\${__pocket_runner%% *}"
      elif [[ "\$__pocket_shebang" == "#!"* ]]; then
        __pocket_runner="\${__pocket_shebang#\\#\\!}"
        __pocket_runner="\${__pocket_runner## }"
        __pocket_runner="\${__pocket_runner##*/}"
        __pocket_runner="\${__pocket_runner%% *}"
      else
        __pocket_runner="bash"
      fi
      ;;
  esac

  local __pocket_remaining=("\${__pocket_args[@]:\$__pocket_depth}")
  local __pocket_cmd="\${__pocket_args[*]:0:\$__pocket_depth}"
  local __pocket_all_dirs
  __pocket_all_dirs=\$(IFS=:; echo "\${__pocket_dirs[*]}")

  POCKET_COMMAND="\$__pocket_cmd" \\
  POCKET_CLI_NAME="\$__pocket_name" \\
  POCKET_SCRIPT_PATH="\$__pocket_script" \\
  POCKET_DIR="\$__pocket_dir" \\
  POCKET_DIRS="\$__pocket_all_dirs" \\
  \$__pocket_runner \${__pocket_runner_args:+"\$__pocket_runner_args"} "\$__pocket_script" "\${__pocket_remaining[@]}"
}
`;
}
