import { EXTENSION_PROBE_ORDER } from "../../core/runner.js";

interface FishTemplateOptions {
  readonly name: string;
  readonly dirs: readonly string[];
}

/**
 * Generate a fish shell function that acts as a CLI dispatcher.
 */
export function generateFishFunction(options: FishTemplateOptions): string {
  const { name, dirs } = options;
  const dirsDecl = dirs.map((d) => `"${d}"`).join(" ");
  const extList = EXTENSION_PROBE_ORDER.map((e) => `"${e}"`).join(" ");

  return `# Generated by pocket — https://github.com/rodrigopsasaki/pocketcli

function ${name}
  set -l __pocket_dirs ${dirsDecl}
  set -l __pocket_name "${name}"

  switch "$argv[1]"
    case help doctor completions create
      set -l dir_flags
      for d in $__pocket_dirs; set -a dir_flags --dir $d; end
      command pocket $argv[1] --name $__pocket_name $dir_flags
      return $status
    case ""
      set -l dir_flags
      for d in $__pocket_dirs; set -a dir_flags --dir $d; end
      command pocket help --name $__pocket_name $dir_flags
      return $status
  end

  set -l __pocket_exts ${extList}
  set -l __pocket_script ""
  set -l __pocket_dir ""
  set -l __pocket_depth 0
  set -l __pocket_argc (count $argv)

  for __pocket_d in $__pocket_dirs
    for __pocket_i in (seq $__pocket_argc -1 1)
      set -l __pocket_path "$__pocket_d"
      set -l __pocket_ok 1

      for __pocket_j in (seq 1 (math "$__pocket_i - 1"))
        set __pocket_path "$__pocket_path/$argv[$__pocket_j]"
        if not test -d "$__pocket_path"
          set __pocket_ok 0
          break
        end
      end
      test $__pocket_ok -eq 0; and continue

      set -l __pocket_base "$__pocket_path/$argv[$__pocket_i]"

      for __pocket_ext in $__pocket_exts
        if test -f "$__pocket_base.$__pocket_ext"
          set __pocket_script "$__pocket_base.$__pocket_ext"
          set __pocket_dir "$__pocket_d"
          set __pocket_depth $__pocket_i
          break
        end
      end
      test -n "$__pocket_script"; and break

      if test -f "$__pocket_base"; and not test -d "$__pocket_base"
        set __pocket_script "$__pocket_base"
        set __pocket_dir "$__pocket_d"
        set __pocket_depth $__pocket_i
        break
      end
    end
    test -n "$__pocket_script"; and break
  end

  if test -z "$__pocket_script"
    echo "$__pocket_name: command not found: $argv" >&2
    echo "Run '$__pocket_name help' to see available commands." >&2
    return 127
  end

  set -l __pocket_runner ""
  set -l __pocket_runner_args
  switch "$__pocket_script"
    case "*.sh" "*.bash"; set __pocket_runner bash
    case "*.zsh";         set __pocket_runner zsh
    case "*.py";          set __pocket_runner python3
    case "*.rb";          set __pocket_runner ruby
    case "*.js";          set __pocket_runner node
    case "*.ts";          set __pocket_runner npx; set __pocket_runner_args tsx
    case "*.php";         set __pocket_runner php
    case "*.pl";          set __pocket_runner perl
    case "*"
      set -l __pocket_shebang (head -1 "$__pocket_script" 2>/dev/null)
      if string match -q "#!/usr/bin/env *" "$__pocket_shebang"
        set __pocket_runner (string replace "#!/usr/bin/env " "" "$__pocket_shebang" | string split " ")[1]
      else if string match -q "#!*" "$__pocket_shebang"
        set __pocket_runner (basename (string replace "#!" "" "$__pocket_shebang" | string trim | string split " ")[1])
      else
        set __pocket_runner bash
      end
  end

  set -l __pocket_remaining
  if test $__pocket_depth -lt $__pocket_argc
    set __pocket_remaining $argv[(math "$__pocket_depth + 1")..$__pocket_argc]
  end
  set -l __pocket_cmd (string join " " $argv[1..$__pocket_depth])

  set -x POCKET_COMMAND "$__pocket_cmd"
  set -x POCKET_CLI_NAME "$__pocket_name"
  set -x POCKET_SCRIPT_PATH "$__pocket_script"
  set -x POCKET_DIR "$__pocket_dir"
  set -x POCKET_DIRS (string join ":" $__pocket_dirs)

  $__pocket_runner $__pocket_runner_args "$__pocket_script" $__pocket_remaining
  set -l __pocket_status $status

  set -e POCKET_COMMAND POCKET_CLI_NAME POCKET_SCRIPT_PATH POCKET_DIR POCKET_DIRS
  return $__pocket_status
end
`;
}
