import { EXTENSION_PROBE_ORDER } from "../../core/runner.js";

interface ZshTemplateOptions {
  readonly name: string;
  readonly dirs: readonly string[];
}

/**
 * Generate a zsh shell function that acts as a CLI dispatcher.
 * The function does greedy longest-match against the filesystem,
 * auto-detects runners from file extensions, and sets POCKET_* env vars.
 */
export function generateZshFunction(options: ZshTemplateOptions): string {
  const { name, dirs } = options;
  const dirsArray = dirs.map((d) => `"${d}"`).join(" ");
  const extProbe = EXTENSION_PROBE_ORDER.map((e) => `"${e}"`).join(" ");

  return `# Generated by pocket — https://github.com/rodrigopsasaki/pocketcli
# eval "$(pocket init zsh --name ${name} ${dirs.map((d) => `--dir ${d}`).join(" ")})"

function ${name}() {
  local -a __pocket_dirs=(${dirsArray})
  local __pocket_name="${name}"

  # Built-in commands delegate to the pocket binary
  case "\$1" in
    help|doctor|completions|create)
      local -a __pocket_dir_flags=(); for __pocket_d in "\${__pocket_dirs[@]}"; do __pocket_dir_flags+=(--dir "\$__pocket_d"); done
      command pocket "\$1" --name "\$__pocket_name" "\${__pocket_dir_flags[@]}"
      return \$?
      ;;
    "")
      local -a __pocket_dir_flags=(); for __pocket_d in "\${__pocket_dirs[@]}"; do __pocket_dir_flags+=(--dir "\$__pocket_d"); done
      command pocket help --name "\$__pocket_name" "\${__pocket_dir_flags[@]}"
      return \$?
      ;;
  esac

  local -a __pocket_exts=(${extProbe})
  local __pocket_script="" __pocket_dir="" __pocket_depth=0

  for __pocket_d in "\${__pocket_dirs[@]}"; do
    local __pocket_max=\$#

    # Greedy: try longest match first (deepest path), then shorter
    for (( __pocket_i=__pocket_max; __pocket_i>=1; __pocket_i-- )); do
      local __pocket_path="\$__pocket_d"
      local __pocket_ok=1

      # Build directory path from segments 1..(i-1)
      for (( __pocket_j=1; __pocket_j<__pocket_i; __pocket_j++ )); do
        __pocket_path="\$__pocket_path/\${(P)__pocket_j}"
        if [[ ! -d "\$__pocket_path" ]]; then
          __pocket_ok=0
          break
        fi
      done
      [[ \$__pocket_ok -eq 0 ]] && continue

      # Try the i-th argument as a script file (with each known extension)
      local __pocket_leaf="\${(P)__pocket_i}"
      local __pocket_base="\$__pocket_path/\$__pocket_leaf"

      for __pocket_ext in "\${__pocket_exts[@]}"; do
        if [[ -f "\$__pocket_base.\$__pocket_ext" ]]; then
          __pocket_script="\$__pocket_base.\$__pocket_ext"
          __pocket_dir="\$__pocket_d"
          __pocket_depth=\$__pocket_i
          break 3
        fi
      done

      # Try extensionless file
      if [[ -f "\$__pocket_base" && ! -d "\$__pocket_base" ]]; then
        __pocket_script="\$__pocket_base"
        __pocket_dir="\$__pocket_d"
        __pocket_depth=\$__pocket_i
        break 2
      fi
    done
  done

  if [[ -z "\$__pocket_script" ]]; then
    echo "\$__pocket_name: command not found: \$*" >&2
    echo "Run '\$__pocket_name help' to see available commands." >&2
    return 127
  fi

  # Determine runner from file extension
  local __pocket_runner="" __pocket_runner_args=""
  case "\$__pocket_script" in
    *.sh|*.bash) __pocket_runner="bash" ;;
    *.zsh)       __pocket_runner="zsh" ;;
    *.py)        __pocket_runner="python3" ;;
    *.rb)        __pocket_runner="ruby" ;;
    *.js)        __pocket_runner="node" ;;
    *.ts)        __pocket_runner="npx" __pocket_runner_args="tsx" ;;
    *.php)       __pocket_runner="php" ;;
    *.pl)        __pocket_runner="perl" ;;
    *)
      # Read shebang for extensionless files
      local __pocket_shebang
      __pocket_shebang=\$(head -1 "\$__pocket_script" 2>/dev/null)
      if [[ "\$__pocket_shebang" == "#!/usr/bin/env "* ]]; then
        __pocket_runner="\${__pocket_shebang#\\#\\!/usr/bin/env }"
        __pocket_runner="\${__pocket_runner%% *}"
      elif [[ "\$__pocket_shebang" == "#!"* ]]; then
        __pocket_runner="\${__pocket_shebang#\\#\\!}"
        __pocket_runner="\${__pocket_runner## }"
        __pocket_runner="\${__pocket_runner##*/}"
        __pocket_runner="\${__pocket_runner%% *}"
      else
        __pocket_runner="bash"
      fi
      ;;
  esac

  # Build the remaining args (everything after the matched command segments)
  local -a __pocket_remaining=("\${@:$(( __pocket_depth + 1 ))}")
  local __pocket_cmd="\${*:1:\$__pocket_depth}"

  # Execute with POCKET_* environment variables
  POCKET_COMMAND="\$__pocket_cmd" \\
  POCKET_CLI_NAME="\$__pocket_name" \\
  POCKET_SCRIPT_PATH="\$__pocket_script" \\
  POCKET_DIR="\$__pocket_dir" \\
  POCKET_DIRS="\${(j.:.)__pocket_dirs}" \\
  "\$__pocket_runner" \${__pocket_runner_args:+"\$__pocket_runner_args"} "\$__pocket_script" "\${__pocket_remaining[@]}"
}
`;
}
